### ISSUE TITLE
SQLAlchemy 2 DeclarativeBase is not supported

### ISSUE THREAD

**Issue by kasium** [maurerle/eralchemy2#19]
When using render_er with a class extending DeclarativeBase an error is raised, because `switch_input_class_to_method` cannot handle `DeclarativeAttributeIntercept`. I'm happy to give a PR a try

**Comment by maurerle** [comment]
Do you have a short example which uses this?
Would be cool, if you could submit it along to a PR for it :+1: 

But just a small example would help too!

**Comment by kasium** [comment]
Sure. You can find an offical example here: https://docs.sqlalchemy.org/en/20/orm/mapping_styles.html#declarative-mapping. I solved it local with this code
```py
from eralchemy2 import main as eralchemy2_main
eralchemy2_main.switch_input_class_to_method[
        "DeclarativeAttributeIntercept"
] = eralchemy2_main.declarative_to_intermediary
```
