### ISSUE TITLE
How does this handles spaces in the table or column names

### ISSUE THREAD

**Issue by moltra** [maurerle/eralchemy2#22]
I have not tried with this version yet, but I cannot get the original version to accept table or column names with spaces in them.  I have tried single quotes, double quotes as referenced in the original er document.  But I keeps getting and error that the column already exists, using only the 1st word of the multiple words in the table or column name.

I have not tried this version yet, because I am trying to do this for work and I can install the conda version (old version) not this version.  I am going to have to set this up on my personal computer to test this version.

**Comment by maurerle** [comment]
Thats true, the regex in `models.py` does not allow whitespace currently when converting from `*.er` to something else.
It works when reading from a database.

I don't know what would be a good character set of allowed tokens.
I will have a look on how to fix this in the next days.

**Comment by maurerle** [comment]
This is fixed with 65b8f8327f49f7439ba13f327a29493ae6ec4312
Can you confirm this @moltra ?

**Comment by maurerle** [comment]
As this is fixed, I am closing the issue - if there is still any issue, just post again :)
