### ISSUE TITLE
graphviz/cgraph.h not found (Linux aarch64)

### ISSUE THREAD

**Issue by alexwilson1** [maurerle/eralchemy2#28]
Installing on aarch64 (Linux) gives the error described in [this](https://github.com/pygraphviz/pygraphviz/issues/155) thread:
```bash
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DSWIG_PYTHON_STRICT_BYTE_CHAR -I/usr/local/include/python3.10 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-aarch64-cpython-310/pygraphviz/graphviz_wrap.o
      pygraphviz/graphviz_wrap.c:3020:10: fatal error: graphviz/cgraph.h: No such file or directory
       3020 | #include "graphviz/cgraph.h"
            |          ^~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```
Workaround for me was to run this:

```bash
sudo apt update
sudo apt install graphviz libgraphviz-dev
export C_INCLUDE_PATH="/usr/include/graphviz:$C_INCLUDE_PATH"
export LIBRARY_PATH="/usr/lib/aarch64-linux-gnu/graphviz:$LIBRARY_PATH"
pip install --use-pep517 pygraphviz
pip install eralchemy2
```

**Comment by maurerle** [comment]
Thats not a problem of eralchemy2 but of the pygraphviz installation.

I thought that installing libgraphviz-dev is enough.
Is that not the case?
Should we update installation instructions to make it clearer that this is required?

**Comment by TortoiseHam** [comment]
On Mac you may need to run: `pip install --use-pep517 --config-settings=--global-option=build_ext --config-settings=--global-option="-I$(brew --prefix graphviz)/include" --config-settings=--global-option="-L$(brew --prefix graphviz)/lib" pygraphviz`

**Comment by maurerle** [comment]
When using conda, you can also simply install with `conda install -c conda-forge eralchemy2`, which also brings the graphviz dependency through pygraphviz from conda :)

The latest release also includes install instructions in the REAMDE.
I will therefore close this issue.
