### ISSUE TITLE
Linking Relationship Lines to Their Columns

### ISSUE THREAD

**Issue by TortoiseHam** [maurerle/eralchemy2#30]
First off, thanks for making this fork to keep the package alive. 

When I generate a diagram with several tables, where Table A Column B foreign keys to Table C Column D, I had expected to get a line from B to D. Instead a line is drawn from A to C without regard for which rows of the tables contain B and D. Is this the kind of thing that might be easily fixable or is it more of a fundamental limitation of the underlying libraries being used to generate the diagram?

**Comment by qwenger** [comment]
I also think that would be interesting, but I share your concerns.

Also a quick note on that: compound keys would have to be handled specifically.

**Comment by TortoiseHam** [comment]
Yeah, it seems like this isn't supported anywhere, which feels like a missed opportunity to me. I would think that compound keys could just be handled by using a line from each source to each target (or maybe from each source into a central line for travel and then fanning out again at the target). But if none of the underlying libraries support it then it would probably take a while to implement.

**Comment by maurerle** [comment]
Actually the ERD tool from pgAdmin4 does this
![image](https://github.com/maurerle/eralchemy2/assets/25026204/e5d621ff-b1e4-4793-a50d-13070a842e04)

As can also be seen here:
https://www.pgadmin.org/docs/pgadmin4/8.5/erd_tool.html#the-table-link

Though exporting this into json and png is possible, I don't think this helps with this issue.
But you might want to consider this if this fits your needs.

**Comment by TortoiseHam** [comment]
@maurerle, Awesome, thanks for pointing this out :)

**Comment by maurerle** [comment]
Fixed in eralchemy/eralchemy which is soon to be released: https://github.com/eralchemy/eralchemy
