### ISSUE TITLE
Should it be moved to the sqlAlchemy organization ? 

### ISSUE THREAD

**Issue by 12rambau** [maurerle/eralchemy2#47]
I saw that you fork this repository from a staled project and my fear is that once you get less time to work on it this one will also end up on stale. What do you think of asking to add it to the sqlAlchemy organization ? 
IT would get more exposure and with it more people could help you maintain it.

**Comment by maurerle** [comment]
Thanks for this good idea,
this surely might be the case, though the current work of maintaining this project is not in fear of ending staled for now :)
Also note, that this risk is not automatically mitigated by changing to `sqlalchemy/eralchemy2` - if noone cares and likes to maintain together, things might end stale anyway - though the probability of this is surely reduced.

I would surely be very happy to have this as an official sqlalchemy repo :)
So please ask them! :)

**Comment by 12rambau** [comment]
I'm also trying to contact the original developer of the lib so you can merge your dev and use the original name.

**Comment by 12rambau** [comment]
This repository is not a fork from Alexis Benoist one ? I don't see him in the contributor list, which might geopardize the transfer to a bigger organisation.

**Comment by maurerle** [comment]
@12rambau thanks for this effort. I already tried contacting @Alexis_Benoist through mail and github, but maybe you have better luck.

This project started as a fork, he is the author all commits prior to my fork. He is also noted and attributed in the README.
I asked Github to remove the "forked" note, so that this repository can have its own issue tracker..

**Comment by maurerle** [comment]
I just checked, it was not the issue tracker (which is possible on forks).
When issuing a PR to a fork, github tries to issue the PR to the upstream instead.
This led to this PR: https://github.com/Alexis-benoist/eralchemy/pull/99#issuecomment-1824136436 which references the discussion about the unability to change the default upstream repository:
https://github.com/orgs/community/discussions/11729

For now the only way to handle this, is to request github to detach the fork: https://github.com/orgs/community/discussions/11729#discussioncomment-4403106 (which I did)

**Comment by 12rambau** [comment]
So  am now maintainer of the original project and the pypi feed. I will open an issue on the sqlalchemy organisation but before that would it be possible to make a merge request back to the original repo ? My objective is to do a transfer from there so we keep all the metadata (specifically the stars)

**Comment by maurerle** [comment]
I wonder how you achieved this, while I never got any response.
I created a Pull request to it (which I would merge by hand on the cli to just fast-forward the commits) - you can also just push my changes on top of the repo.

However I do not know what would be the best approach to maintain this in the future, as the eralchemy2 package already has many more downloads than eralchemy according to
https://pypistats.org/packages/eralchemy2

https://pypistats.org/packages/eralchemy

Eventually it would be best to just turn eralchemy to an alias to eralchemy2 in pypi?

**Comment by 12rambau** [comment]
my little experience is that numbered lib are confusing (hello pypdf) so I would do the other way around with a big disclaimer in the last release of this one (eventually a warning at import state)

**Comment by maurerle** [comment]
so one way forward would be to create a new org eralchemy/eralchemy, let the project live there and maintain it in a way which merges the eralchemy2 back to eralchemy?

**Comment by maurerle** [comment]
This is done as of https://github.com/eralchemy/eralchemy/issues/119
